
(()=>{'use strict';
const D=window.APP_DATA;if(!D)throw new Error('Datos no cargados');
const $=s=>document.querySelector(s), view=$('#view'), modal=$('#modal'), modalBody=$('#modalBody');
const store={get(k,d){try{return JSON.parse(localStorage.getItem('vw340_'+k))??d}catch{return d}},set(k,v){localStorage.setItem('vw340_'+k,JSON.stringify(v))}};
let route=location.hash.slice(1)||'home', cityFilter='Todos';
const esc=s=>String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
const fmtDate=s=>new Intl.DateTimeFormat('es-ES',{weekday:'short',day:'numeric',month:'short'}).format(new Date(s+'T12:00:00'));
function toast(t){const e=$('#toast');e.textContent=t;e.hidden=false;clearTimeout(window.__tt);window.__tt=setTimeout(()=>e.hidden=true,2200)}
function navActive(){document.querySelectorAll('.bottom button').forEach(b=>b.classList.toggle('active',b.dataset.go===route))}
function go(r){route=r;location.hash=r;render();window.scrollTo(0,0)}
function hero(img,ey,title,text,buttons=''){return `<section class="hero"><img src="${img}" alt=""><div class="hero-copy"><div class="eyebrow">${ey}</div><h1>${title}</h1><p>${text}</p>${buttons?`<div class="actions">${buttons}</div>`:''}</div></section>`}
function placeCard(p){return `<article class="card"><button class="cover" data-place="${p.id}"><img src="${p.photo}" alt="${esc(p.name)}" loading="lazy"><div class="card-body"><span class="chip">${esc(p.city)} · ${esc(p.tag)}</span><h3>${esc(p.name)}</h3><p>${esc(p.summary)}</p></div></button></article>`}
function home(){const done=store.get('doneDays',[]), today=D.trip[0];return hero('images/hero.webp','VW340 · Viaje familiar','Portugal 2026','Diez días en camper entre mercados, palacios, pueblos medievales, Atlántico y el Duero.',`<button class="btn secondary" data-day="${today.id}">Abrir el plan</button><button class="btn" data-go="route">Ver la ruta</button>`)+`<section class="stats"><div class="stat"><b>10</b><span>días</span></div><div class="stat"><b>7</b><span>paradas</span></div><div class="stat"><b>${done.length}/10</b><span>jornadas</span></div></section><section class="section"><div class="section-head"><div><h2>El viaje completo</h2><p>Todo lo necesario, día por día.</p></div><button class="linkbtn" data-go="route">Ver todo</button></div><div class="timeline">${D.trip.slice(0,4).map(dayRow).join('')}</div></section><section class="section"><div class="section-head"><div><h2>Imprescindibles</h2><p>Fichas con historia, consejos, horarios y mapa.</p></div><button class="linkbtn" data-go="explore">Explorar</button></div><div class="grid">${['feira','pena','obidos-vila','nazare-sitio','costa-nova','ribeira'].map(id=>placeCard(D.places.find(p=>p.id===id))).join('')}</div></section>`}
function dayRow(d){return `<article class="day"><img src="${d.photo}" alt=""><button data-day="${d.id}"><small>${fmtDate(d.date)} · ${esc(d.city)}</small><h3>${esc(d.title)}</h3><p>${esc(d.meta)}</p></button></article>`}
function routePage(){return hero('images/lisboa.webp','10–19 agosto','La ruta completa','Desde Chiclana hasta Lisboa, Sintra, Óbidos, Nazaré, Aveiro, Oporto y Burgos.',`<a class="btn secondary" target="_blank" rel="noopener" href="https://www.google.com/maps/dir/Chiclana+de+la+Frontera/Lisboa/Sintra/%C3%93bidos/Nazar%C3%A9/Aveiro/Porto/Burgos/Sabadell">Abrir ruta en Maps</a>`)+`<section class="section"><div class="section-head"><div><h2>Plan diario</h2><p>Pulsa una jornada para ver agenda y lugares.</p></div></div><div class="timeline">${D.trip.map(dayRow).join('')}</div></section><section class="section"><h2>Ciudades</h2><div class="grid">${D.cities.map(c=>`<article class="card"><button class="cover" data-city="${esc(c.name)}"><img src="${c.photo}" alt="${esc(c.name)}"><div class="card-body"><span class="chip">${c.count} lugares</span><h3>${esc(c.name)}</h3><p>${esc(c.subtitle)}</p></div></button></article>`).join('')}</div></section>`}
function explore(){const cities=['Todos',...new Set(D.places.map(p=>p.city))];const q=store.get('search','');let ps=D.places.filter(p=>(cityFilter==='Todos'||p.city===cityFilter)&&(`${p.name} ${p.city} ${p.tag} ${p.summary}`.toLowerCase().includes(q.toLowerCase())));return `<section class="section"><div class="section-head"><div><h2>Explorar</h2><p>${D.places.length} lugares con información detallada.</p></div></div><div class="searchbox"><input id="searchInput" value="${esc(q)}" placeholder="Buscar lugar, barrio, mercado…" aria-label="Buscar"></div><div class="filters">${cities.map(c=>`<button data-filter="${esc(c)}" class="${cityFilter===c?'active':''}">${esc(c)}</button>`).join('')}</div><div class="grid" id="placeGrid">${ps.length?ps.map(placeCard).join(''):'<div class="empty">No hay resultados.</div>'}</div></section>`}
function girls(){const checks=store.get('missions',{});const person=n=>{const arr=D.missions[n],completed=arr.filter((_,i)=>checks[n+'_'+i]).length;return `<section class="panel"><div class="section-head"><div><h2>${n}</h2><p>${completed} de ${arr.length} misiones</p></div><b>${Math.round(completed/arr.length*100)}%</b></div><div class="progress"><span style="width:${completed/arr.length*100}%"></span></div>${arr.map((m,i)=>`<label class="mission"><input type="checkbox" data-mission="${n}_${i}" ${checks[n+'_'+i]?'checked':''}><span>${esc(m)}</span></label>`).join('')}</section>`};return hero('images/sintra.webp','Pasaporte de exploradoras','Greta & Maria','Retos visuales para convertir cada parada en una aventura.',`<button class="btn secondary" data-go="explore">Abrir lugares</button>`)+person('Greta')+person('Maria')}
function more(){return `<section class="section"><h2>Tu viaje</h2><p>Todo se guarda en este dispositivo.</p><div class="grid"><article class="card"><button class="cover" data-tool="journal"><img src="images/porto.webp" alt=""><div class="card-body"><h3>Bitácora</h3><p>Recuerdos, puntuación y foto de cada día.</p></div></button></article><article class="card"><button class="cover" data-tool="expenses"><img src="images/restaurantes.webp" alt=""><div class="card-body"><h3>Gastos</h3><p>Control sencillo por categorías.</p></div></button></article><article class="card"><button class="cover" data-tool="checklist"><img src="images/nazare-camper.webp" alt=""><div class="card-body"><h3>Checklist camper</h3><p>Preparación, documentación y salida.</p></div></button></article><article class="card"><button class="cover" data-tool="backup"><img src="images/regreso.webp" alt=""><div class="card-body"><h3>Copia de seguridad</h3><p>Exportar o restaurar todos los datos.</p></div></button></article></div></section><section class="panel"><h3>Instalar en el iPhone</h3><p>En Safari: Compartir → Añadir a pantalla de inicio. Tras la primera carga, la guía y las fotografías quedan disponibles sin conexión.</p></section>`}
function render(){navActive();if(route==='home')view.innerHTML=home();else if(route==='route')view.innerHTML=routePage();else if(route==='explore')view.innerHTML=explore();else if(route==='girls')view.innerHTML=girls();else view.innerHTML=more();view.focus({preventScroll:true})}
function openModal(html){modalBody.innerHTML=html;modal.hidden=false;document.body.style.overflow='hidden'}function closeModal(){modal.hidden=true;document.body.style.overflow='';modalBody.innerHTML=''}
function openPlace(id){const p=D.places.find(x=>x.id===id);if(!p)return;openModal(`<div class="detail-hero"><img src="${p.photo}" alt="${esc(p.name)}"><div class="detail-title"><div class="eyebrow">${esc(p.city)} · ${esc(p.tag)}</div><h1>${esc(p.name)}</h1></div></div><div class="detail-content"><p>${esc(p.summary)}</p><div class="place-meta"><span>◷ ${esc(p.duration)}</span><span>€ ${esc(p.price)}</span><span>☀ ${esc(p.best)}</span></div><div class="actions"><a class="btn" href="${p.map}" target="_blank" rel="noopener">Cómo llegar</a><a class="btn ghost" href="${p.official}" target="_blank" rel="noopener">Web oficial</a></div><h3>Por qué merece la pena</h3><p>${esc(p.history)}</p><h3>Horario orientativo</h3><p>${esc(p.time)}</p><h3>Consejos prácticos</h3><ul>${p.tips.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><div class="panel"><h3>Reto para las niñas</h3><p>${esc(p.kids)}</p></div><h3>Qué comer cerca</h3><p>${esc(p.food)}</p><p><small>Horarios y precios pueden cambiar. Comprueba siempre la web oficial antes de ir.</small></p></div>`)}
function openDay(id){const d=D.trip.find(x=>x.id===id),done=store.get('doneDays',[]);const journal=store.get('journal',{});openModal(`<div class="detail-hero"><img src="${d.photo}" alt=""><div class="detail-title"><div class="eyebrow">${fmtDate(d.date)} · ${esc(d.city)}</div><h1>${esc(d.title)}</h1></div></div><div class="detail-content"><p>${esc(d.meta)}</p><h3>Agenda</h3><div class="panel">${d.items.map(x=>`<p>${esc(x)}</p>`).join('')}</div>${d.places.length?`<h3>Lugares del día</h3><div class="grid">${d.places.map(id=>placeCard(D.places.find(p=>p.id===id))).join('')}</div>`:''}<div class="actions"><button class="btn" data-toggle-day="${d.id}">${done.includes(d.id)?'Marcar como pendiente':'Completar jornada'}</button><button class="btn ghost" data-journal-day="${d.id}">Escribir recuerdo</button></div>${journal[d.id]?`<div class="panel"><b>Tu recuerdo</b><p>${esc(journal[d.id].text)}</p><p>${'★'.repeat(Number(journal[d.id].rating||0))}</p></div>`:''}</div>`)}
function journal(dayId){const all=store.get('journal',{}),d=D.trip.find(x=>x.id===dayId)||D.trip[0],j=all[d.id]||{};openModal(`<div class="detail-content"><h1>Bitácora</h1><label>Día</label><select id="jday">${D.trip.map(x=>`<option value="${x.id}" ${x.id===d.id?'selected':''}>${fmtDate(x.date)} · ${esc(x.title)}</option>`).join('')}</select><div class="panel"><label>¿Qué recordaremos?</label><textarea id="jtext" placeholder="Escribe aquí…">${esc(j.text||'')}</textarea><label>Valoración</label><select id="jrating">${[1,2,3,4,5].map(n=>`<option ${Number(j.rating)===n?'selected':''} value="${n}">${'★'.repeat(n)}</option>`).join('')}</select><div class="actions"><button class="btn" data-save-journal>Guardar recuerdo</button></div></div></div>`)}
function expenses(){const a=store.get('expenses',[]),total=a.reduce((s,x)=>s+Number(x.amount),0);openModal(`<div class="detail-content"><h1>Gastos</h1><div class="stat"><b>${total.toLocaleString('es-ES',{style:'currency',currency:'EUR'})}</b><span>total registrado</span></div><div class="panel"><label>Concepto</label><input id="exName" placeholder="Camping, gasolina, comida…"><label>Categoría</label><select id="exCat"><option>Transporte</option><option>Alojamiento</option><option>Comida</option><option>Entradas</option><option>Otros</option></select><label>Importe (€)</label><input id="exAmount" type="number" step="0.01"><div class="actions"><button class="btn" data-add-expense>Añadir</button></div></div><div>${a.map((x,i)=>`<div class="expense"><span><b>${esc(x.name)}</b><small> · ${esc(x.cat)}</small></span><b>${Number(x.amount).toLocaleString('es-ES',{style:'currency',currency:'EUR'})}</b><button class="linkbtn danger" data-del-expense="${i}">Eliminar</button></div>`).join('')||'<p class="empty">Todavía no hay gastos.</p>'}</div></div>`)}
const checklistDefault=['DNI y tarjetas sanitarias','Documentación y seguro de la camper','Permiso de circulación e ITV','Cargadores y baterías externas','Botiquín y medicación','Calzos, cable eléctrico y adaptadores','Agua, gas y nivel de combustible','Ropa de baño y calzado cómodo','Entradas reservadas','Descargar mapas sin conexión'];
function checklist(){const c=store.get('checklist',{});openModal(`<div class="detail-content"><h1>Checklist camper</h1><div class="panel">${checklistDefault.map((x,i)=>`<label class="mission"><input type="checkbox" data-check="${i}" ${c[i]?'checked':''}><span>${esc(x)}</span></label>`).join('')}</div></div>`)}
function backup(){openModal(`<div class="detail-content"><h1>Copia de seguridad</h1><div class="panel"><p>Descarga un archivo con la bitácora, gastos, misiones y checklist.</p><div class="actions"><button class="btn" data-export>Exportar datos</button><label class="btn ghost">Importar archivo<input id="importFile" type="file" accept="application/json" hidden></label><button class="btn ghost danger" data-reset>Reiniciar app</button></div></div></div>`)}
document.addEventListener('click',e=>{const b=e.target.closest('button,a');if(!b)return;if(b.dataset.go)go(b.dataset.go);if(b.dataset.place)openPlace(b.dataset.place);if(b.dataset.day)openDay(b.dataset.day);if(b.dataset.city){cityFilter=b.dataset.city;go('explore')}if(b.dataset.filter){cityFilter=b.dataset.filter;render()}if(b.dataset.close!==undefined)closeModal();if(b.dataset.tool==='journal')journal();if(b.dataset.tool==='expenses')expenses();if(b.dataset.tool==='checklist')checklist();if(b.dataset.tool==='backup')backup();if(b.dataset.toggleDay){let a=store.get('doneDays',[]);a=a.includes(b.dataset.toggleDay)?a.filter(x=>x!==b.dataset.toggleDay):[...a,b.dataset.toggleDay];store.set('doneDays',a);toast('Jornada actualizada');openDay(b.dataset.toggleDay)}if(b.dataset.journalDay)journal(b.dataset.journalDay);if(b.dataset.saveJournal!==undefined){const all=store.get('journal',{}),id=$('#jday').value;all[id]={text:$('#jtext').value,rating:$('#jrating').value};store.set('journal',all);toast('Recuerdo guardado');closeModal()}if(b.dataset.addExpense!==undefined){const name=$('#exName').value.trim(),amount=parseFloat($('#exAmount').value);if(!name||!amount)return toast('Completa concepto e importe');const a=store.get('expenses',[]);a.push({name,cat:$('#exCat').value,amount});store.set('expenses',a);expenses()}if(b.dataset.delExpense!==undefined){const a=store.get('expenses',[]);a.splice(Number(b.dataset.delExpense),1);store.set('expenses',a);expenses()}if(b.dataset.export!==undefined){const payload={version:1,exported:new Date().toISOString()};for(const k of ['doneDays','journal','missions','expenses','checklist'])payload[k]=store.get(k,k==='expenses'||k==='doneDays'?[]:{});const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='VW340-portugal-datos.json';a.click();URL.revokeObjectURL(u)}if(b.dataset.reset!==undefined&&confirm('¿Borrar todos los datos guardados?')){Object.keys(localStorage).filter(k=>k.startsWith('vw340_')).forEach(k=>localStorage.removeItem(k));closeModal();render();toast('Datos reiniciados')}});
document.addEventListener('input',e=>{if(e.target.id==='searchInput'){const q=e.target.value;store.set('search',q);const ps=D.places.filter(p=>(cityFilter==='Todos'||p.city===cityFilter)&&(`${p.name} ${p.city} ${p.tag} ${p.summary}`.toLowerCase().includes(q.toLowerCase())));const g=$('#placeGrid');if(g)g.innerHTML=ps.length?ps.map(placeCard).join(''):'<div class="empty">No hay resultados.</div>'}});document.addEventListener('change',e=>{if(e.target.dataset.mission){const x=store.get('missions',{});x[e.target.dataset.mission]=e.target.checked;store.set('missions',x);render();toast('Misión actualizada')}if(e.target.dataset.check!==undefined){const x=store.get('checklist',{});x[e.target.dataset.check]=e.target.checked;store.set('checklist',x)}if(e.target.id==='jday')journal(e.target.value);if(e.target.id==='importFile'){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);for(const k of ['doneDays','journal','missions','expenses','checklist'])if(x[k]!==undefined)store.set(k,x[k]);closeModal();render();toast('Datos restaurados')}catch{toast('Archivo no válido')}};r.readAsText(f)}});
$('#searchBtn').addEventListener('click',()=>go('explore'));window.addEventListener('hashchange',()=>{route=location.hash.slice(1)||'home';render()});modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
render();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.warn));
})()
