(()=>{'use strict';
const D=window.APP_DATA;if(!D)throw new Error('Datos no cargados');
const $=s=>document.querySelector(s),view=$('#view'),modal=$('#modal'),modalBody=$('#modalBody');
const store={get(k,d){try{return JSON.parse(localStorage.getItem('vw340_'+k))??d}catch{return d}},set(k,v){localStorage.setItem('vw340_'+k,JSON.stringify(v))}};
let route=location.hash.slice(1)||'home',cityFilter='Todos';
const esc=s=>String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]));
const fmtDate=s=>new Intl.DateTimeFormat('es-ES',{day:'numeric',month:'long'}).format(new Date(s+'T12:00:00'));
const icon=(name)=>({pin:'<svg viewBox="0 0 24 24"><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0z"/><circle cx="12" cy="10" r="2.5"/></svg>',calendar:'<svg viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 3v4M17 3v4M3 10h18M8 14h.01M12 14h.01M16 14h.01M8 18h.01M12 18h.01"/></svg>',city:'<svg viewBox="0 0 24 24"><path d="M4 21V9l6-3v15M10 21V3l10 4v14M2 21h20M14 9h2M14 13h2M14 17h2M6 12h1M6 16h1"/></svg>',star:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="m12 7 1.4 3.1 3.4.4-2.5 2.3.7 3.4-3-1.7-3 1.7.7-3.4-2.5-2.3 3.4-.4z"/></svg>'}[name]||'');
function toast(t){const e=$('#toast');e.textContent=t;e.hidden=false;clearTimeout(window.__tt);window.__tt=setTimeout(()=>e.hidden=true,2200)}
function navActive(){document.querySelectorAll('.bottom button[data-go]').forEach(b=>b.classList.toggle('active',b.dataset.go===route))}
function go(r){route=r;location.hash=r;render();window.scrollTo({top:0,behavior:'smooth'})}
function hero(img,ey,title,text,buttons=''){return `<section class="editorial-hero"><img src="${img}" alt=""><div class="hero-copy"><div class="eyebrow">${ey}</div><h1>${title}</h1><p>${text}</p>${buttons?`<div class="actions">${buttons}</div>`:''}</div></section>`}
function placeCard(p){return `<article class="card"><button class="cover" data-place="${p.id}"><img src="${p.photo}" alt="${esc(p.name)}" loading="lazy"><div class="card-body"><span class="chip">${esc(p.city)} · ${esc(p.tag)}</span><h3>${esc(p.name)}</h3><p>${esc(p.summary)}</p></div></button></article>`}
function dayRow(d){return `<article class="day"><img src="${d.photo}" alt=""><button data-day="${d.id}"><small>${fmtDate(d.date)} · ${esc(d.city)}</small><h3>${esc(d.title)}</h3><p>${esc(d.meta)}</p></button></article>`}
function home(){const done=store.get('doneDays',[]),today=D.trip[0],next=D.trip[1]||D.trip[0];return `<div class="home-shell">
<section class="feature-hero"><img src="images/lisboa.webp" alt="Lisboa"><div class="feature-copy"><span class="day-pill">Día 2 · 11 agosto</span><h1>Lisboa</h1><p>Descubre el encanto de la capital portuguesa</p><button class="hero-cta" data-day="${today.id}">Ver plan del día&nbsp; ›</button></div></section>
<div class="dots" aria-hidden="true"><i class="active"></i><i></i><i></i></div>
<section class="section"><h2 class="section-title">Resumen del viaje</h2><div class="summary-grid">
<div class="summary-item">${icon('pin')}<b>2.640 km</b><small>Recorrido</small></div>
<div class="summary-item">${icon('calendar')}<b>10 días</b><small>10–19 agosto</small></div>
<div class="summary-item">${icon('city')}<b>8 ciudades</b><small>Por descubrir</small></div>
<div class="summary-item">${icon('star')}<b>64 misiones</b><small>Greta & Maria</small></div>
</div></section>
<section class="section"><h2 class="section-title">Próxima parada</h2><button class="next-card cover" data-day="${next.id}" style="border:0;width:100%;text-align:left;color:inherit;padding:0"><img src="${next.photo}" alt="${esc(next.city)}"><span class="next-copy"><h3>${esc(next.city)}</h3><p>Mañana · ${fmtDate(next.date)}<br>${esc(next.meta)}</p></span></button></section>
<section class="section"><div class="section-head"><div><h2>El viaje completo</h2><p>${done.length} de 10 jornadas completadas</p></div><button class="linkbtn" data-go="route">Ver todo</button></div><div class="timeline">${D.trip.slice(0,3).map(dayRow).join('')}</div></section>
<section class="section"><div class="section-head"><div><h2>Para no perderse</h2><p>Selección familiar de imprescindibles</p></div><button class="linkbtn" data-go="explore">Explorar</button></div><div class="grid">${['feira','pena','obidos-vila'].map(id=>D.places.find(p=>p.id===id)).filter(Boolean).map(placeCard).join('')}</div></section>
</div>`}
function routePage(){return hero('images/hero.webp','10–19 agosto','Nuestra ruta','Una aventura familiar entre ciudades, palacios, costa atlántica y pueblos con historia.',`<a class="btn secondary" target="_blank" rel="noopener" href="https://www.google.com/maps/dir/Chiclana+de+la+Frontera/Lisboa/Sintra/%C3%93bidos/Nazar%C3%A9/Aveiro/Porto/Burgos/Sabadell">Abrir ruta en Maps</a>`)+`<section class="section"><div class="section-head"><div><h2>Plan diario</h2><p>Pulsa cada jornada para abrirla completa</p></div></div><div class="timeline">${D.trip.map(dayRow).join('')}</div></section><section class="section"><div class="section-head"><div><h2>Ciudades</h2><p>Guías fotográficas con todo el detalle</p></div></div><div class="grid">${D.cities.map(c=>`<article class="city-card"><img src="${c.photo}" alt="${esc(c.name)}"><button data-city="${esc(c.name)}"><span><div class="eyebrow">${c.count} lugares</div><h3>${esc(c.name)}</h3><p>${esc(c.subtitle)}</p></span></button></article>`).join('')}</div></section>`}
function explore(){const cities=['Todos',...new Set(D.places.map(p=>p.city))],q=store.get('search','');const ps=D.places.filter(p=>(cityFilter==='Todos'||p.city===cityFilter)&&(`${p.name} ${p.city} ${p.tag} ${p.summary}`.toLowerCase().includes(q.toLowerCase())));return `<section class="section"><div class="section-head"><div><h2>Explorar</h2><p>${D.places.length} lugares con información completa</p></div></div><div class="searchbox"><input id="searchInput" value="${esc(q)}" placeholder="Buscar lugar, barrio, mercado…" aria-label="Buscar"></div><div class="filters">${cities.map(c=>`<button data-filter="${esc(c)}" class="${cityFilter===c?'active':''}">${esc(c)}</button>`).join('')}</div><div class="grid" id="placeGrid">${ps.length?ps.map(placeCard).join(''):'<div class="empty">No hay resultados.</div>'}</div></section>`}
function girls(){const checks=store.get('missions',{});const person=n=>{const arr=D.missions[n],completed=arr.filter((_,i)=>checks[n+'_'+i]).length;return `<section class="panel"><div class="section-head"><div><h2>${n}</h2><p>${completed} de ${arr.length} misiones</p></div><b>${Math.round(completed/arr.length*100)}%</b></div><div class="progress"><span style="width:${completed/arr.length*100}%"></span></div>${arr.map((m,i)=>`<label class="mission"><input type="checkbox" data-mission="${n}_${i}" ${checks[n+'_'+i]?'checked':''}><span>${esc(m)}</span></label>`).join('')}</section>`};return hero('images/sintra.webp','Pasaporte de exploradoras','Greta & Maria','Dos maneras de mirar el mismo viaje. Retos, hallazgos y recuerdos para completar juntas.',`<button class="btn secondary" data-go="explore">Descubrir lugares</button>`)+person('Greta')+person('Maria')}
function more(){return hero('images/porto.webp','Todo vuestro','La bitácora','Recuerdos, gastos, preparativos y copia de seguridad en un único lugar.')+`<section class="section"><div class="grid"><article class="card"><button class="cover" data-tool="journal"><img src="images/porto-ribeira.webp" alt=""><div class="card-body"><h3>Bitácora</h3><p>Escribe lo que no quieres olvidar.</p></div></button></article><article class="card"><button class="cover" data-tool="expenses"><img src="images/restaurantes.webp" alt=""><div class="card-body"><h3>Gastos</h3><p>Control por conceptos y categorías.</p></div></button></article><article class="card"><button class="cover" data-tool="checklist"><img src="images/nazare-camper.webp" alt=""><div class="card-body"><h3>Checklist camper</h3><p>Todo listo antes de arrancar.</p></div></button></article><article class="card"><button class="cover" data-tool="backup"><img src="images/regreso.webp" alt=""><div class="card-body"><h3>Copia de seguridad</h3><p>Exporta o recupera todos los datos.</p></div></button></article></div></section><section class="panel"><h3>Instalar en el iPhone</h3><p>Abre la web en Safari, pulsa Compartir y elige “Añadir a pantalla de inicio”.</p></section>`}
function render(){navActive();if(route==='home')view.innerHTML=home();else if(route==='route')view.innerHTML=routePage();else if(route==='explore')view.innerHTML=explore();else if(route==='girls')view.innerHTML=girls();else view.innerHTML=more();view.focus({preventScroll:true})}
function openModal(html){modalBody.innerHTML=html;modal.hidden=false;document.body.style.overflow='hidden'}function closeModal(){modal.hidden=true;document.body.style.overflow='';modalBody.innerHTML=''}
function openPlace(id){const p=D.places.find(x=>x.id===id);if(!p)return;openModal(`<div class="detail-hero"><img src="${p.photo}" alt="${esc(p.name)}"><div class="detail-title"><div class="eyebrow">${esc(p.city)} · ${esc(p.tag)}</div><h1>${esc(p.name)}</h1></div></div><div class="detail-content"><p>${esc(p.summary)}</p><div class="place-meta"><span>◷ ${esc(p.duration)}</span><span>€ ${esc(p.price)}</span><span>☀ ${esc(p.best)}</span></div><div class="actions"><a class="btn" href="${p.map}" target="_blank" rel="noopener">Cómo llegar</a><a class="btn ghost" href="${p.official}" target="_blank" rel="noopener">Web oficial</a></div><h3>Por qué merece la pena</h3><p>${esc(p.history)}</p><h3>Horario orientativo</h3><p>${esc(p.time)}</p><h3>Consejos prácticos</h3><ul>${p.tips.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><div class="panel"><h3>Reto para las niñas</h3><p>${esc(p.kids)}</p></div><h3>Qué comer cerca</h3><p>${esc(p.food)}</p><p><small>Los horarios y precios pueden cambiar. Comprueba la web oficial antes de ir.</small></p></div>`)}
function openDay(id){const d=D.trip.find(x=>x.id===id),done=store.get('doneDays',[]),journalData=store.get('journal',{});openModal(`<div class="detail-hero"><img src="${d.photo}" alt=""><div class="detail-title"><div class="eyebrow">${fmtDate(d.date)} · ${esc(d.city)}</div><h1>${esc(d.title)}</h1></div></div><div class="detail-content"><p>${esc(d.meta)}</p><h3>Agenda del día</h3><div class="panel">${d.items.map(x=>`<p>${esc(x)}</p>`).join('')}</div>${d.places.length?`<h3>Lugares del día</h3><div class="grid">${d.places.map(id=>D.places.find(p=>p.id===id)).filter(Boolean).map(placeCard).join('')}</div>`:''}<div class="actions"><button class="btn" data-toggle-day="${d.id}">${done.includes(d.id)?'Marcar como pendiente':'Completar jornada'}</button><button class="btn ghost" data-journal-day="${d.id}">Escribir recuerdo</button></div>${journalData[d.id]?`<div class="panel"><b>Tu recuerdo</b><p>${esc(journalData[d.id].text)}</p><p>${'★'.repeat(Number(journalData[d.id].rating||0))}</p></div>`:''}</div>`)}
function journal(dayId){const all=store.get('journal',{}),d=D.trip.find(x=>x.id===dayId)||D.trip[0],j=all[d.id]||{};openModal(`<div class="detail-hero"><img src="${d.photo}" alt=""><div class="detail-title"><div class="eyebrow">Bitácora familiar</div><h1>${esc(d.city)}</h1></div></div><div class="detail-content"><label>Día</label><select id="jday">${D.trip.map(x=>`<option value="${x.id}" ${x.id===d.id?'selected':''}>${fmtDate(x.date)} · ${esc(x.title)}</option>`).join('')}</select><div class="panel"><label>¿Qué recordaremos?</label><textarea id="jtext" placeholder="Escribe aquí…">${esc(j.text||'')}</textarea><label>Valoración</label><select id="jrating">${[1,2,3,4,5].map(n=>`<option ${Number(j.rating)===n?'selected':''} value="${n}">${'★'.repeat(n)}</option>`).join('')}</select><div class="actions"><button class="btn" data-save-journal>Guardar recuerdo</button></div></div></div>`)}
function expenses(){const a=store.get('expenses',[]),total=a.reduce((s,x)=>s+Number(x.amount),0);openModal(`<div class="detail-content"><h1>Gastos</h1><div class="panel"><b style="font-size:32px">${total.toLocaleString('es-ES',{style:'currency',currency:'EUR'})}</b><p>Total registrado</p></div><div class="panel"><label>Concepto</label><input id="exName" placeholder="Camping, gasolina, comida…"><label>Categoría</label><select id="exCat"><option>Transporte</option><option>Alojamiento</option><option>Comida</option><option>Entradas</option><option>Otros</option></select><label>Importe (€)</label><input id="exAmount" type="number" step="0.01"><div class="actions"><button class="btn" data-add-expense>Añadir</button></div></div><div>${a.map((x,i)=>`<div class="expense"><span><b>${esc(x.name)}</b><small> · ${esc(x.cat)}</small></span><b>${Number(x.amount).toLocaleString('es-ES',{style:'currency',currency:'EUR'})}</b><button class="linkbtn danger" data-del-expense="${i}">Eliminar</button></div>`).join('')||'<p class="empty">Todavía no hay gastos.</p>'}</div></div>`)}
const checklistDefault=['DNI y tarjetas sanitarias','Documentación y seguro de la camper','Permiso de circulación e ITV','Cargadores y baterías externas','Botiquín y medicación','Calzos, cable eléctrico y adaptadores','Agua, gas y nivel de combustible','Ropa de baño y calzado cómodo','Entradas reservadas','Descargar mapas sin conexión'];
function checklist(){const c=store.get('checklist',{});openModal(`<div class="detail-content"><h1>Checklist camper</h1><div class="panel">${checklistDefault.map((x,i)=>`<label class="mission"><input type="checkbox" data-check="${i}" ${c[i]?'checked':''}><span>${esc(x)}</span></label>`).join('')}</div></div>`)}
function backup(){openModal(`<div class="detail-content"><h1>Copia de seguridad</h1><div class="panel"><p>Descarga un archivo con la bitácora, gastos, misiones y checklist.</p><div class="actions"><button class="btn" data-export>Exportar datos</button><label class="btn ghost">Importar archivo<input id="importFile" type="file" accept="application/json" hidden></label><button class="btn ghost danger" data-reset>Reiniciar app</button></div></div></div>`)}
document.addEventListener('click',e=>{const b=e.target.closest('button,a');if(!b)return;if(b.dataset.go)go(b.dataset.go);if(b.dataset.place)openPlace(b.dataset.place);if(b.dataset.day)openDay(b.dataset.day);if(b.dataset.city){cityFilter=b.dataset.city;go('explore')}if(b.dataset.filter){cityFilter=b.dataset.filter;render()}if(b.dataset.close!==undefined)closeModal();if(b.dataset.tool==='journal')journal();if(b.dataset.tool==='expenses')expenses();if(b.dataset.tool==='checklist')checklist();if(b.dataset.tool==='backup')backup();if(b.dataset.toggleDay){let a=store.get('doneDays',[]);a=a.includes(b.dataset.toggleDay)?a.filter(x=>x!==b.dataset.toggleDay):[...a,b.dataset.toggleDay];store.set('doneDays',a);toast('Jornada actualizada');openDay(b.dataset.toggleDay)}if(b.dataset.journalDay)journal(b.dataset.journalDay);if(b.dataset.saveJournal!==undefined){const all=store.get('journal',{}),id=$('#jday').value;all[id]={text:$('#jtext').value,rating:$('#jrating').value};store.set('journal',all);toast('Recuerdo guardado');closeModal()}if(b.dataset.addExpense!==undefined){const name=$('#exName').value.trim(),amount=parseFloat($('#exAmount').value);if(!name||!amount)return toast('Completa concepto e importe');const a=store.get('expenses',[]);a.push({name,cat:$('#exCat').value,amount});store.set('expenses',a);expenses()}if(b.dataset.delExpense!==undefined){const a=store.get('expenses',[]);a.splice(Number(b.dataset.delExpense),1);store.set('expenses',a);expenses()}if(b.dataset.export!==undefined){const payload={version:2,exported:new Date().toISOString()};for(const k of ['doneDays','journal','missions','expenses','checklist'])payload[k]=store.get(k,k==='expenses'||k==='doneDays'?[]:{});const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='VW340-portugal-datos.json';a.click();URL.revokeObjectURL(u)}if(b.dataset.reset!==undefined&&confirm('¿Borrar todos los datos guardados?')){Object.keys(localStorage).filter(k=>k.startsWith('vw340_')).forEach(k=>localStorage.removeItem(k));closeModal();render();toast('Datos reiniciados')}});
document.addEventListener('input',e=>{if(e.target.id==='searchInput'){const q=e.target.value;store.set('search',q);const ps=D.places.filter(p=>(cityFilter==='Todos'||p.city===cityFilter)&&(`${p.name} ${p.city} ${p.tag} ${p.summary}`.toLowerCase().includes(q.toLowerCase())));const g=$('#placeGrid');if(g)g.innerHTML=ps.length?ps.map(placeCard).join(''):'<div class="empty">No hay resultados.</div>'}});
document.addEventListener('change',e=>{if(e.target.dataset.mission){const x=store.get('missions',{});x[e.target.dataset.mission]=e.target.checked;store.set('missions',x);render();toast('Misión actualizada')}if(e.target.dataset.check!==undefined){const x=store.get('checklist',{});x[e.target.dataset.check]=e.target.checked;store.set('checklist',x)}if(e.target.id==='jday')journal(e.target.value);if(e.target.id==='importFile'){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);for(const k of ['doneDays','journal','missions','expenses','checklist'])if(x[k]!==undefined)store.set(k,x[k]);closeModal();render();toast('Datos restaurados')}catch{toast('Archivo no válido')}};r.readAsText(f)}});
$('#searchBtn').addEventListener('click',()=>go('explore'));$('#menuBtn').addEventListener('click',()=>go('more'));window.addEventListener('hashchange',()=>{route=location.hash.slice(1)||'home';render()});modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
try{render()}catch(err){console.error(err);$('#app').hidden=true;$('#fatal').hidden=false}
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.warn));
})();
